version: '3.9'

services:
  web:
    build: .
    image: api-nauticapass
    ports:
      - "8000:8000"
    environment:
      DB_ENGINE: django.db.backends.postgresql_psycopg2
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: nauticapass
      DB_USER: postgres
      DB_PASSWORD: 123456
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: nauticapass
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
