# Generated by Django 5.2.1 on 2025-06-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_vessel', models.CharField(blank=True, max_length=255, unique=True)),
                ('name_owner', models.CharField(blank=True, max_length=255)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('navigation_type', models.CharField(blank=True, choices=[('barco', 'Barco'), ('ajato', 'Ajato'), ('balsa', 'Balsa'), ('ferry_boat', 'Ferry boat')], max_length=50)),
            ],
        ),
    ]
