# Generated by Django 5.2.1 on 2025-06-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vessel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='name_vessel',
            field=models.CharField(blank=True, error_messages={'unique': 'Está embarcação já existe.'}, max_length=255, unique=True),
        ),
    ]
