# Generated by Django 5.2.1 on 2025-06-11 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vessel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('travel_date', models.DateField()),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('arrival_date', models.DateField()),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages_destination', to='passage.city')),
                ('id_vessel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passages_as_vessel', to='vessel.vessel')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages_origin', to='passage.city')),
            ],
        ),
    ]
