# Generated by Django 5.2.1 on 2025-05-24 03:51

import django.db.models.deletion
import hashid_field.field
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', hashid_field.field.HashidAutoField(alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=9, prefix='', primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('travel_date', models.DateField()),
                ('purchase_time', models.TimeField()),
                ('travel_time', models.TimeField()),
                ('navigation_type', models.CharField(choices=[('barco', 'Barco'), ('ajato', 'Ajato'), ('balsa', 'Balsa'), ('ferry_boat', 'Ferry boat')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='user.user')),
            ],
        ),
    ]
