# Generated by Django 5.2.1 on 2025-05-26 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='id',
            new_name='unique_ticket',
        ),
    ]
