# Generated by Django 5.2.1 on 2025-05-27 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='unique_ticket',
            new_name='id',
        ),
    ]
