# Generated by Django 5.2.1 on 2025-05-28 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_unique_ticket_ticket_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(blank=True, max_length=255)),
                ('destination', models.CharField(blank=True, max_length=255)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('travel_date', models.DateField()),
                ('travel_time', models.TimeField()),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_vessel', models.CharField(blank=True, max_length=255, unique=True)),
                ('name_owner', models.CharField(blank=True, max_length=255)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('navigation_type', models.CharField(blank=True, choices=[('barco', 'Barco'), ('ajato', 'Ajato'), ('balsa', 'Balsa'), ('ferry_boat', 'Ferry boat')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='navigation_type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='travel_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='travel_time',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(choices=[('pix', 'Pix'), ('cash', 'Boleto')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Este email já está sendo usado.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ticket',
            name='passage_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.passage'),
        ),
        migrations.AddField(
            model_name='passage',
            name='capacity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages_as_capacity', to='user.vessel'),
        ),
        migrations.AddField(
            model_name='passage',
            name='id_vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages_as_vessel', to='user.vessel'),
        ),
    ]
