# Generated by Django 5.2.1 on 2025-05-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_passage_vessel_remove_ticket_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rg',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
