# Generated by Django 5.2.1 on 2025-05-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='rg',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
