# Generated by Django 5.2.1 on 2025-05-28 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_cpf_alter_user_phone_alter_user_rg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passage',
            old_name='travel_time',
            new_name='arrival_time',
        ),
    ]
