# Generated by Django 5.2.1 on 2025-05-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_rename_travel_time_passage_arrival_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='departure_date',
        ),
        migrations.AddField(
            model_name='passage',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
