# Generated by Django 5.2.1 on 2025-05-29 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='passage',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages_destination', to='user.city'),
        ),
        migrations.AlterField(
            model_name='passage',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages_origin', to='user.city'),
        ),
    ]
