# Generated by Django 5.2.1 on 2025-05-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_passage_capacity_alter_passage_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
