# Generated by Django 5.2.1 on 2025-06-01 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_passage_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='id_vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passages_as_vessel', to='user.vessel'),
        ),
    ]
