# Generated by Django 5.2.1 on 2025-06-01 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_passage_id_vessel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='id_vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages_as_vessel', to='user.vessel'),
        ),
    ]
