# Generated by Django 5.2.1 on 2025-06-09 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_passage_id_vessel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('acronym', models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='Sigla ISO')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='gender_type',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='passport',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='user.nationality'),
        ),
    ]
