# Generated by Django 5.2.1 on 2025-06-09 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_nationality_user_gender_type_user_passport_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nationality',
        ),
        migrations.AddField(
            model_name='user',
            name='nationality_type',
            field=models.CharField(blank=True, choices=[('brasileiro', 'Brasileiro'), ('estrangeiro', 'Estrangeiro')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='passage',
            name='id_vessel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passages_as_vessel', to='user.vessel'),
        ),
        migrations.DeleteModel(
            name='Nationality',
        ),
    ]
