# Generated by Django 5.2.1 on 2025-06-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_remove_user_nationality_user_nationality_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passage',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='passage',
            name='id_vessel',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='passage_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(blank=True, error_messages={'unique': 'Este CPF já está sendo usado.'}, max_length=14, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='vessel',
        ),
        migrations.DeleteModel(
            name='Passage',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
