# Generated by Django 5.2.1 on 2025-06-11 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.CharField(editable=False, max_length=9, primary_key=True, serialize=False, unique=True)),
                ('purchase_date', models.DateField()),
                ('purchase_time', models.TimeField()),
                ('payment_method', models.CharField(choices=[('pix', 'Pix'), ('cash', 'Boleto')], max_length=10)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('passage_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='passage.passage')),
            ],
        ),
    ]
