# Generated by Django 5.2.1 on 2026-06-28 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('passage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('purchase_date', models.DateField()),
                ('purchase_time', models.TimeField()),
                ('payment_method', models.CharField(choices=[('pix', 'Pix'), ('cash', 'Boleto')], max_length=10)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('passage_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='passage.passage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
