# Generated by Django 5.2.1 on 2025-06-13 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticket_purchase_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='origin',
        ),
    ]
