# Generated by Django 5.2.1 on 2025-06-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_remove_ticket_destination_remove_ticket_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='destination',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
