# Generated by Django 5.2.1 on 2025-06-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_remove_ticket_user_id_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='payment_method',
            field=models.CharField(choices=[('Pix', 'Pix'), ('Boleto', 'Boleto'), ('Débito', 'Débito'), ('Crédito', 'Crédito')], max_length=10),
        ),
    ]
