# Generated by Django 5.2.1 on 2025-06-14 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelItinerary', '0002_initial'),
        ('ticket', '0005_ticket_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='ticket.ticket', verbose_name='Passagem')),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
